### PR TITLE
Lint with flake8

### PR DESCRIPTION
**Pull request by AMeng**
Lint the codebase with flake8.

### CODE REVIEW

**Comment by dicato** [comment]
[My comment](https://github.com/macropin/django-registration/pull/56#issuecomment-171839916) applies here as well.

@AMeng if you are interested, please re-lint the current master branch and either rebase this branch or open a new pull request.

**Comment by AMeng** [comment]
I'll be happy to update this once https://github.com/macropin/django-registration/pull/56 is merged, so that I don't have to rebase again.

**Comment by dicato** [comment]
Sounds like a good plan. :smile:

**Comment by dicato** [comment]
#56 is merged. :smile: Thank you!

**Comment by AMeng** [comment]
@dicato rebased

**Comment by dicato** [comment]
:smile: thanks!

**Pull request merged**
