### PR TITLE
Add initial migration for Django 1.7.

### PR DESCRIPTION
**Pull request by timgraham**

### CODE REVIEW

**Comment by macropin** [comment]
Why were you thinking we should add this? There are no plans to change the schema, and I think this will break on Django < 1.7 if using South.

**Comment by chhantyal** [comment]
Yea, if this is added - South support has to be added.

@macropin It's quite easy to support both south and db.migrations though https://docs.djangoproject.com/en/1.7/topics/migrations/#upgrading-from-south

**Comment by timgraham** [comment]
I ran into a problem upgrading djangoproject.com to Django 1.8 related to having a relationship between a migrated and unmigrated app so this fixes that. I can add the migration as part of the project (done at least temporarily in https://github.com/django/djangoproject.com/pull/373), but though I'd contribute back since this will be needed by Django 1.9 when migrations become compulsory for all apps.

You might consider dropping Django < 1.7 support in the next release of registration as 1.6 support will end when 1.8 is released (~2 months) and 1.4 support will end 6 months after that. I think users using old versions of Django won't need the latest and greatest version of registration.

**Comment by timgraham** [comment]
@macropin any reply? We are about ready to upgrade djangoproject.com to 1.8 and this is a blocking issue (we can add migrations using `settings.MIGRATION_MODULES` if necessary, but that just forces that solution on all your users).

**Comment by jgoclawski** [comment]
@timgraham I support this idea. We'll have to apply your solution in our project if we want to move to Django 1.8 and this issue doesn't get resolved.

**Comment by macropin** [comment]
@timgraham I think it's pragmatic to roll a PyPi release of our current 1.2 and then drop support for earlier versions. I'll try to get that out the door in the next few days. Once that's done I'll merge this in.

**Comment by jose-lpa** [comment]
Guys, I guess since #42 is already merged and those model changes won't hurt the DB schema at all, it would be nice to create the initial migration from that code, instead of from this one. What do you think?

**Comment by timgraham** [comment]
Rebased on master and updated migration. Thanks for the heads up.

**Comment by macropin** [comment]
I've implemented this as well as requisite backwards compatibility for South users. Please test and let me know how you go. A release is imminent so QA would be helpful. Thanks

**Comment by timgraham** [comment]
Works for djangoproject.com on Django 1.8.

**Comment by macropin** [comment]
@timgraham Thanks for the feedback. Now to address #27 and get this release out.

**Pull request closed without merging**
