### PR TITLE
Reset user.date_joined to ensure a full activation interval window

### PR DESCRIPTION
**Pull request by joshblum**

### CODE REVIEW

**Comment by joshblum** [comment]
Addresses #171

**Comment by joshblum** [comment]
@dicato thoughts on this approach?

**Comment by dicato** [comment]
Interesting! I think it's a simple and clever approach. Do you see any side effects for people who use the User's join date in other logic?

**Comment by joshblum** [comment]
Hmm it is possible that others would use this field in logic before registration, perhaps we can leave a note in the documentation and then people can subclass to change `create_inactive_user` if necessary?

**Comment by dicato** [comment]
Alternatively, we could decouple the date joined with the registration expiry date. We would add a field to `RegistrationProfile` for this. Thoughts?

**Comment by joshblum** [comment]
The `user.date_joined` is definitely simpler (which is why I decided to give it a try vs. the data migration) if you think changing the date is a bad idea we can decouple but I'm not sure if it will mess with anything for anyone

**Comment by dicato** [comment]
I honestly don't feel strongly either way. I think under normal circumstances this implementation won't cause any unexpected issues. Maybe someone else has input?

**Comment by joshblum** [comment]
Let's land before the next release if no one comments?

**Comment by dicato** [comment]
👍 absolutely!

**Pull request merged**
