### PR TITLE
Updates pt_BR translation

### PR DESCRIPTION
**Pull request by gabrielssilva**
Updates pt_BR translation messages

### CODE REVIEW

**Comment by joshblum** [comment]
@gabrielssilva thanks for the contribution! Can you branch off of #304 instead of master since there are some translation strings missing as #303 notes. Once you're finished please run `django-admin compilemessages` so the `.mo` file is updated with the new data.

**Comment by gabrielssilva** [comment]
Will do

**Comment by joshblum** [comment]
@gabrielssilva #304 was just merged, so if you rebase master onto your branch you should be good to go just update the `.po` file and recompile the messages

**Comment by gabrielssilva** [comment]
Updated

**Comment by joshblum** [comment]
Thank you so much for contributing!

**Pull request merged**
