### PR TITLE
prevent  RemovedInDjango110Warning

### PR DESCRIPTION
**Pull request by neseleznev**

### CODE REVIEW

**Comment by dicato** [comment]
@neseleznev could you look into the failing builds and provide some context to what this change does?

**Comment by joshblum** [comment]
@neseleznev the test failure is just because of a lint error, so should be easy to fix: https://travis-ci.org/macropin/django-registration/jobs/129872972#L274

Does this PR have any backward compatibility issues?

**Comment by timgraham** [comment]
The purpose of this PR is to address this deprecation in Django 1.8: https://docs.djangoproject.com/en/stable/releases/1.8/#dictionary-and-context-instance-arguments-of-rendering-functions

To keep the request available during template rendering, `request=request` should be added to the `render_to_string()` call. This is a new argument in Django 1.8. I suggest to first drop support for Django 1.7 (https://github.com/macropin/django-registration/issues/190) so we don't have to write code that differs based on the Django version.

**Comment by dicato** [comment]
👍 fixed by #194

**Pull request closed without merging**
