### PR TITLE
Update ko locale

### PR DESCRIPTION
**Pull request by quroom**
ko locale file was not complete.
So I updated it and make pr.

### CODE REVIEW

**Comment by quroom** [comment]
Need to fix fuzzy keyword.
There is sentence should not have "fuzzy" keyword.
So I will fix it soon.
Please wait for update.
If you want to close this pr, You can.
But if you can wait, I will make it ASAP

**Comment by quroom** [comment]
Remove comment out ```#fuzzy```.
Some of codes are used in html file.

**Comment by quroom** [comment]
I updated small changed.
Now it looks well.

**Review by joshblum — APPROVED** [review]
thanks!

**Pull request merged**
