### PR TITLE
Username case insensitive and username to lowercase

### PR DESCRIPTION
**Pull request by pando85**
I think if we do a username case insensitive is important to change user to lowercase for efficiency queries against database.

### CODE REVIEW

**Comment by dicato** [comment]
@pando85 my comments here - https://github.com/macropin/django-registration/pull/235#issuecomment-280356805 - still apply to this new PR.

**Comment by pando85** [comment]
@dicato  reopen #235 and discuss here the new propose to do an lower() before save.

**Comment by joshblum** [comment]
@pando85 are you still working on this? Can you rebase onto master cleanly so we can review your proposed changes?

**Comment by pando85** [comment]
Continue in #251

**Pull request closed without merging**
