### PR TITLE
Dropped Django 1.11 and Python 2.7 support, and fixed deprecation warnings for Django 3.1.

### PR DESCRIPTION
**Pull request by felixxm**

### CODE REVIEW

**Comment by macropin** [comment]
Thanks for this.

My only concern is the extra indent space on wrapped lines. Is there a reason for this? (We should probably have a linter to ensure consistent formatting)

**Comment by felixxm** [comment]
> My only concern is the extra indent space on wrapped lines. Is there a reason for this? (We should probably have a linter to ensure consistent formatting)

I added them because they were reported by `make lint` (used by TravisCI).

**Comment by joshblum** [comment]
@felixxm looks good overall, thanks! Curious why you chose to drop the regular expressions and used `path(...)` instead of `re_path(...)`

**Comment by felixxm** [comment]
`path()` is more readable and simpler, IMO, that's why we add it to Django, to avoid regular expression where they're not necessary (see [release notes](https://docs.djangoproject.com/en/3.1/releases/2.0/#simplified-url-routing-syntax)).

**Comment by felixxm** [comment]
I can prepare later follow up PRs with removing Python 2 shims.

**Comment by joshblum** [comment]
> I can prepare later follow up PRs with removing Python 2 shims.
Sounds great! I'll prepare a release once that is in

**Review by joshblum — APPROVED** [review]

**Comment by felixxm** [comment]
PR with the most obvious changes is ready, #399.

**Pull request merged**
