### PR TITLE
improve README.rst

### PR DESCRIPTION
**Pull request by areski**

### CODE REVIEW

**Comment by areski** [comment]
just small improvements on the readme, cc/ @dicato

**Comment by dicato** [comment]
I like it! I have two thoughts for feedback:

* should we delete the `INSTALL` file?
* should we shuffle the order of installation instructions to promote installing from PyPI with pip as the preferred option?

**Comment by areski** [comment]
Oups forgot to delete the INSTALL, that was my intention.
I can't agree more on your second point!

Thanks

**Comment by dicato** [comment]
Thanks @areski :+1: Merging!

**Comment by areski** [comment]
Thanks :)

**Pull request merged**
