### PR TITLE
Fix south migrations, previous checkin had models that don't exist in…

### PR DESCRIPTION
**Pull request by mick-t**
See

* https://github.com/macropin/django-registration/issues/87#issuecomment-134452825

Mauler's commit has references to models that don't exist, and I presume are custom models for his own project. This should resolve that.

### CODE REVIEW

**Comment by dicato** [comment]
@mick-t I apologize this has sat. Would you be able to rebase this branch so it applies cleanly and retest the migration to ensure it works?

**Comment by dicato** [comment]
After looking through pull request history, I'm going to close this as support to Django 1.7 and South was dropped in #117.

@mick-t if this causes you problems, let's discuss. :smile:

**Comment by mick-t** [comment]
Sorry for not replying soon -- I was away for a few weeks with limited Internet access and am finally back online. :)

I'm still using Django 1.5 with plans to upgrade to 1.9. In the meantime I still need to use Django-registration -- how would you suggest I proceed? 

I can rebase my branch if you like?

**Comment by dicato** [comment]
@mick-t no worries!

I'm honestly not sure the best approach. It was a conscious decision to drop support for Django older than 1.7. If I was running a Django 1.5 project, I'd likely fork this project and add south migrations back.

I'd like for others to weigh in on this as well.

**Comment by mick-t** [comment]
Your fork suggestion is what I was thinking of doing -- I guess that's what
I'll do. Thanks.

**Pull request closed without merging**
