### PR TITLE
Make method signatures consistent for RegistrationView and AcitvationView classes

### PR DESCRIPTION
**Pull request by joshblum**
Address #150

### CODE REVIEW

**Comment by dicato** [comment]
@joshblum thanks for working on this! I left some feedback in the issue - #150

**Comment by joshblum** [comment]
@dicato any changes need to land this?

**Comment by dicato** [comment]
@joshblum - I think it looks great.

**Comment by joshblum** [comment]
Awesome! If you don't mind pushing to pypi it would be super helpful since I can clean up some of my subclassing code with the new `RegistrationView` signatures :)

**Pull request merged**
