### PR TITLE
fix issue #27

### PR DESCRIPTION
**Pull request by laginha**
Use `USERNAME_FIELD` attribute to define the `RegistrationForm` meta fields (useful for custom user models)

### CODE REVIEW

**Comment by AMeng** [comment]
Would be good to add a test for this.

**Comment by macropin** [comment]
Looks good, but as @AMeng said a test using a custom User model would be a good idea. Can you please add one.

**Comment by AMeng** [comment]
Added a test here: https://github.com/macropin/django-registration/pull/61

**Comment by AMeng** [comment]
I added a couple of tests for this in https://github.com/macropin/django-registration/pull/61. As I mentioned there this fix really just stops the form import from breaking in versions of Django < 1.8. After that it does actually let you subclass the form successfully. I guess that should be documented.

**Pull request merged**
