### PR TITLE
Add title to active.html

### PR DESCRIPTION
**Pull request by joshblum**
Address #159

### CODE REVIEW

**Comment by dicato** [comment]
:+1: Thank you!

What's your opinion (or the general consensus) on updating the changelog to reflect template changes or these sort of minor changes in general?

**Comment by joshblum** [comment]
I don't really know for sure but adding one line saying the fix happened can't hurt :)

**Comment by dicato** [comment]
:smile: OK!

Please update the changelog and I'll merge!

**Comment by joshblum** [comment]
Cool :) Should be good to go

**Comment by dicato** [comment]
Thanks!

**Pull request merged**
