### PR TITLE
Prepare for 1.3 release

### LINKED ISSUE #131: Prepare for 1.3 release
**This is a work in progress...**

## todo

* [x] update `CHANGELOG`
* [x] update version number to `1.3`
* [x] merge #94

### PR DESCRIPTION
**Pull request by dicato**
This prepares @macropin to cut a 1.3 release to PyPI. I've updated the version number and went through both commit and pull requests since the previous release in order to help update the `CHANGELOG`. I'd greatly appreciate any feedback on items I've missed. GitHub has a couple helpful searches I used for this:

* [closed pull requests sorted by last updated](https://github.com/macropin/django-registration/pulls?page=1&q=is%3Apr+is%3Aclosed+sort%3Aupdated-desc)
* [78 commits since version 1.2](https://github.com/macropin/django-registration/compare/v1.2...master)

### todo

* [x] update version number
* [x] update `CHANGELOG`
* [x] merge #141 - I'd like to sneak this small change in 1.3

Fix #131

### CODE REVIEW

**Comment by dicato** [comment]
@mcrowson and @areski if you have the time, the `CHANGELOG` could use a review! Let me know if there are items I've missed.

Additionally, if there is any other pre-release items I've missed I'm all ears. :smile:

**Comment by areski** [comment]
What about adding:
* New resend_activation_mail method to RegistrationManager
* Re-enable Python 3.3 support (trivial)
* Thai translation

Otherwise the Changelog is concise and clean, all good with me! 
It might be best in the future that changelog update are part of each important PR.

**Comment by mcrowson** [comment]
@dicato looks great to me

**Comment by dicato** [comment]
@macropin I think this is ready to go! After tests pass, I'll let you merge since you need to push to PyPI. :+1:

**Pull request merged**
