### PR TITLE
Update faq.rst

### PR DESCRIPTION
**Pull request by vocaviking**
Edit concerning a problem I had, and spend around 2 hours searching for the solution.

### CODE REVIEW

**Comment by dicato** [comment]
@vocaviking could you explain the issue you had? Which templates where causing you issues?

**Comment by vocaviking** [comment]
I wanted to write custom templates for all the views. To do so, I put my template files in the usual places. However for some views, django used the admin templates instead of mine for no apparent reason. As it turns out, you can fix it, by editing the INSTALLED_APPS in settings.py
(Hope this makes sense to you)

**Comment by dicato** [comment]
Was this happening specifically for password reset templates? I can see that happening.

**Comment by vocaviking** [comment]
Indeed.

**Pull request merged**
