### PR TITLE
Remove _RequestPassingFormView (BACKWARDS-INCOMPATIBLE)

### PR DESCRIPTION
**Pull request by AMeng**
This change is backwards-incompatible
---

Fixes https://github.com/macropin/django-registration/issues/39 by removing the unnecessary `_RequestPassingFormView` class. This will be backwards-incompatible for anyone who has sub-classed the views and passed around the `request` object in the old way.

A few other minor clean-up changes:

 * Limit code under `try` blocks to only that which raises the exception.
 * Remove extra whitespace.
 * Ensure newlines at end of `.py` files.
 * Remove commented-out code.

### CODE REVIEW

**Comment by dicato** [comment]
So, unfortunately these changes did not make it into 1.3. As this predates my involvement, I'd like to get @macropin to weigh in on if this pull request is still valid. If so, let's merge it and make 1.4 happen much faster than 1.3.

**Comment by macropin** [comment]
Yeah, lets roll this out in 1.4 sooner rather than later. Happy to push another release next week.

**Comment by dicato** [comment]
@AMeng could you rebase this on current master?

**Comment by AMeng** [comment]
@dicato Rebased with master.

**Comment by dicato** [comment]
Awesome! Thank you. I'll review.

**Pull request merged**
